# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parser_tree_vis.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParserTree(object):
    def setupUi(self, ParserTree):
        ParserTree.setObjectName("ParserTree")
        ParserTree.resize(1500, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("parser.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ParserTree.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(ParserTree)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1501, 1001))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1499, 999))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(ParserTree)
        QtCore.QMetaObject.connectSlotsByName(ParserTree)

    def retranslateUi(self, ParserTree):
        _translate = QtCore.QCoreApplication.translate
        ParserTree.setWindowTitle(_translate("ParserTree", "ParserTree"))
